bettercrative/classrooms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, BooleanField
from wtforms.validators import InputRequired, Length, ValidationError, Optional
from bettercrative.models import Classroom


# Teacher can create an empty classroom with a unique name
class ClassroomForm(FlaskForm):
    name = TextAreaField('Title', validators=[InputRequired(), Length(max=60, message='Must be shorter than 60 characters')])

    def validate_name(self, name):
        name = Classroom.query.filter_by(name=name.data).first()
        if name:
            raise ValidationError('That name has already been taken. Please choose another.')

    submitClass = SubmitField('Create Classroom')


# Student enters a classroom by inputting the unique classroom name
class EnterClassroomForm(FlaskForm):
    room_id = StringField('Room ID', validators=[InputRequired()])
    submit = SubmitField('Enter Classroom')


# Teacher can add an existing quiz or create a new one to be added to the current classroom
class AddQuizForm(FlaskForm):
    quiz = SelectField('Choose a Quiz', coerce=int, validators=[InputRequired('Please select a quiz.')])
    submit = SubmitField('Add Quiz')


class StudentForm(FlaskForm):
    name = StringField('Fill in Name here',validators=[InputRequired(), Length(min=3, max=20)])
    submit = SubmitField('Submit')


class SetActiveForm(FlaskForm):
    require_usernames = BooleanField('Require student usernames?', validators=[Optional()])
    generate_qr = BooleanField('Generate QR code for student sign-in?', validators=[Optional()])
    submit = SubmitField('Set Active')
    # TODO other options we want to have for active quizzes

bettercrative/classrooms/routes.py
from flask import (render_template, url_for, flash,
                   redirect, Blueprint,session,
                   request, make_response, jsonify)
from flask_login import current_user, login_required
from sqlalchemy import exists, and_
from collections import defaultdict
from bettercrative import db
from bettercrative.users.routes import users, quizzes
from bettercrative.quizzes.routes import quizzes, quiz
from bettercrative.classrooms.response_handling import *
from bettercrative.classrooms.forms import ClassroomForm, EnterClassroomForm, AddQuizForm, StudentForm, SetActiveForm
from bettercrative.models import Classroom, Quiz, Response, Question, assoc, Answer, Student

classrooms = Blueprint('classrooms', __name__)


@classrooms.route("/classroom/new", methods=['GET', 'POST'])
@login_required
def new_classroom():
    """ Create a new classroom. """
    classForm = ClassroomForm()
    if classForm.validate_on_submit():
        classroom = Classroom(name=classForm.name.data, owner=current_user)
        db.session.add(classroom)
        db.session.commit()
        flash(u'New classroom \"' + classroom.name + '\" created!', 'success')
        return redirect(url_for('classrooms.classroom', classroom_id=classroom.id))


# TODO exception handling for student enter classroom w/o active quiz
@classrooms.route("/classroom/enter", methods=['GET', 'POST'])
def enter_classroom():
    """ Student sign-in to classroom. Classroom must have an active quiz. """
    form = EnterClassroomForm()
    if form.validate_on_submit():
        classroom = Classroom.query.filter_by(name=form.room_id.data).first()
        if classroom and classroom.active_quiz:
            print("-------------------------------------------------------------------")
            print("ADDING STUDENT")
            print("-------------------------------------------------------------------")
            student = Student(quiz_reference = classroom.active_quiz)
            db.session.add(student)
            db.session.commit()
            if classroom.username_required:    
                print("-------------------------------------------------------------------")
                print("STUDENTS NEED TO PUT A USERNAME HERE")
                print("-------------------------------------------------------------------")   
                return redirect(url_for('classrooms.student_name', classroom_id = classroom.id, student=student.id))
            else:   
                return redirect(url_for('classrooms.take_quiz', classroom_id=classroom.id,student=student.id))
        else:
            flash(u'A classroom does not exist with that name. Please try again.', 'danger')
    return render_template('enter_classroom.html', title='get in chief', form=form)

@classrooms.route('/classroom/student_name', methods=['GET','POST'])
def student_name():
    args = request.args

    if 'classroom_id' not in args and 'student' not in args:
        raise('classroom_id key and student key not found')

    form = StudentForm()
  
    
    if form.validate_on_submit():
        
        student = Student.query.filter_by(id=int(args['student'])).first()
        student.name = form.name.data
        db.session.commit()
        return redirect(url_for('classrooms.take_quiz', classroom_id= args['classroom_id'], student= student.id))
    return render_template('student_name.html', form = form, classroom_id = args['classroom_id'], student= args['student'])

@classrooms.route("/classroom/<int:classroom_id>", methods=['GET', 'POST'])
def classroom(classroom_id):
    """ 
    Display the given classroom's dashboard.

    Parameters:
            classroom_id (int): the ID of the classroom to display
    """
    classroom = Classroom.query.get_or_404(classroom_id)
    activeform = SetActiveForm()
    
    if current_user.is_authenticated:
        form = ClassroomForm()
        # this is so the "view results" button only shows up if there's something to view
        has_responses = bool(Response.query.filter_by(classroom_host_id=classroom_id).first())
        return render_template('classroom.html', title=classroom.name, classroom=classroom, form=form, has_responses=has_responses, activeform=activeform)
    else:
        quiz = classroom.active_quiz
        student = Student()

        return render_template('take_quiz.html', title='TakeQuiz', classroom=classroom, quiz=quiz, student=student)


@classrooms.route("/classroom/<int:classroom_id>/add_quiz", methods=['GET', 'POST'])
@login_required
def add_quiz(classroom_id):
    """
    Add a quiz to a classroom. Can choose an existing quiz that belongs to the user or create a new one.

    Parameters:
            classroom_id (int): the ID of the classroom to add a quiz to
    """
    classroom = Classroom.query.get_or_404(classroom_id)

    # Setting up the form
    form = AddQuizForm()

    # add default option to "create a quiz" in the dropdown
    default_choice = (0, "Create a Quiz")
    quizzes = Quiz.query.filter_by(user_id=current_user.id).filter(~exists().where(and_(assoc.c.quiz_id == Quiz.id, assoc.c.classroom_id == classroom.id)))

    # putting all quizzes of that user (that have names set) in the list
    quiz_list = [(quiz.id, quiz.name) for quiz in quizzes if quiz.name]
    quiz_list.append(default_choice)
    list.reverse(quiz_list)
    form.quiz.choices = quiz_list

    # Handle POST request
    if form.validate_on_submit():
        # get chosen quiz's ID from the form, grab that quiz and attach it to the current classroom
        quiz_id = form.quiz.data
        if quiz_id == 0:
            return redirect(url_for('quizzes.new_quiz', classroom_id=classroom_id))
        else:
            quiz = Quiz.query.filter_by(id=quiz_id).first()
            classroom.added_quizzes.append(quiz)
            db.session.commit()
            flash(u'Quiz \"' + quiz.name + '\" added to \"' + classroom.name + '\"!', 'success')
            return redirect(url_for('classrooms.classroom', classroom_id=classroom.id))

    # Handle GET request
    return render_template('add_quiz.html', title=classroom.name, classroom=classroom, form=form, quiz_list=quiz_list)


# TODO: currently there is a bug where if you click on the nav bar the change gets reset, however, routing to the
#  page separately or refreshing the page does not break the active-ness
@classrooms.route("/classroom/<int:classroom_id>/<int:quiz_id>/set_active", methods=['GET', 'POST'])
@login_required
def set_active(classroom_id, quiz_id):
    """
    Sets the given quiz as active in the classroom it's in.
    
    Parameters: 
            quiz_id (int): the ID of the quiz to set active
            classroom_id (int): the ID of the classroom to make it active in
    """
    print(request.form)
    classroom = Classroom.query.get_or_404(classroom_id)
    quiz = Quiz.query.get_or_404(quiz_id)
    
    activeform = SetActiveForm()
    
    if activeform.validate_on_submit():
        
        classroom.username_required = activeform.require_usernames.data
        classroom.generate_qr = activeform.generate_qr.data
        classroom.active_quiz = quiz_id
        quiz.is_active = classroom.id
        db.session.commit()
        flash(u'Quiz \"' + quiz.name + '\" is now active in \"' + classroom.name + '\"!', 'success')

    return redirect(url_for('classrooms.classroom', classroom_id=classroom.id))


@classrooms.route('/classroom/unset_and_edit', methods=['POST'])
@login_required
def unset_and_edit():
    form = request.form
    if 'quiz_id' not in form:
        raise('quiz_id key is not found')
    
    quiz = Quiz.query.filter_by(id=int(form['quiz_id'])).first()
    quiz.unset()
    return redirect( url_for('quizzes.quiz', quiz_id=quiz.id))


@classrooms.route('/classroom/unset', methods = ['POST'])
@login_required
def unset():
   
    form = request.form
    if 'quiz_id' not in form and 'classroom_id' not in form:
        raise('quiz_id key is not found')
    
    quiz = Quiz.query.filter_by(id = int(form['quiz_id'])).first()
    quiz.unset()

    return redirect( url_for('users.quizzes'))


@classrooms.route("/classroom/<int:classroom_id>/remove_active", methods=['GET', 'POST'])
@login_required
def remove_active(classroom_id):
    """ Sets the given quiz to inactive in the current classroom.
    
        Parameters: 
                classroom_id (int): the ID of the classroom to inactive the quiz in
    """
    if classroom_id is None:
        raise Exception('No \'classroom_id\' supplied!')

    classroom = Classroom.query.get_or_404(classroom_id)
    quiz = Quiz.query.get_or_404(classroom.active_quiz)
    quiz.is_active = None
    classroom.active_quiz = None
    db.session.commit()
    flash(u'Quiz \"' + quiz.name + '\" unset as active in classroom \"' + classroom.name + '\"!', 'success')

    return redirect(url_for('classrooms.classroom', classroom_id=classroom.id))


@classrooms.route("/classroom/remove_quiz/<int:classroom_id>/<int:quiz_id>", methods=['GET', 'POST'])
@login_required
def remove_quiz(classroom_id, quiz_id):
    """ Removes the given quiz from the given classroom.

        Parameters:
                classroom_id (int): the ID of the classroom to remove the quiz from
                quiz_id (int): the ID of the quiz to be removed
    """

    classroom = Classroom.query.get(classroom_id)
    quiz = Quiz.query.get(quiz_id)
    classroom.added_quizzes.remove(quiz)
    db.session.commit()
    flash(u'Quiz Removed!', 'success')

    return redirect(url_for('classrooms.classroom', classroom_id=classroom_id))


@classrooms.route("/classroom/correct_answer", methods=['GET', 'POST'])
def correct_answer():
    args = request.args

    if 'response_id' not in args:
        raise KeyError('response_id key not found')

bettercrative/main/routes.py
from flask import render_template, Blueprint, make_response, url_for, redirect, request, flash
from flask_login import current_user

from bettercrative import db, bcrypt
from bettercrative.models import User, Quiz, Classroom, Question
from bettercrative.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                       RequestResetForm, ResetPasswordForm)
from bettercrative.classrooms.forms import ClassroomForm, EnterClassroomForm
from bettercrative.quizzes.forms import QuizForm

main = Blueprint('main', __name__)


@main.route('/',  methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def home():
    """ Displays the "home" page. """
    if current_user.is_authenticated:
        return render_template('user_home.html', classForm=ClassroomForm(), quizForm=QuizForm())
    else:
        return render_template('home.html')


@main.route('/about')
def about():
    """ Displays the "about" page. """
    return render_template('about.html')


@main.route("/<page_name>")
def other_page(page_name):
    """ 404 error routes """
    response = make_response(render_template('404.html'), 404)
    return render_template('404.html')

bettercrative/templates/about.html
{% extends "layout.html" %}

{% block content %}



{% endblock %}

bettercrative/templates/classroom.html
{% extends "layout.html" %}

{% block content %}

<div id="classroom-container">
	<div class="titlebar" style="border-bottom:1px solid black;">
		<div id="classroom-title-display" class="input-group float-left" style="width: max-content;">
			<input type="text" class="form-control" placeholder="{{ classroom.name }}" disabled>
			<div class="input-group-append">
				<button onclick="javascript:toggleEditClassroomTitle();" class="btn btn-outline-info"><i class="fas fa-edit"></i></button>
			</div>
		</div>

		<form style="display: none;" id="classroom-title-edit" action="{{ url_for('classrooms.edit_classroom_name', classroom_id=classroom.id) }}">
			<div style="width: max-content;" class="input-group">
				{{form.hidden_tag()}}
				<input id="classroomname-content-3" class="form-control" maxlength="60" name="name" required placeholder="{{ classroom.name }}" value="{{ classroom.name }}">
				<div class="input-group-append">
					<button type="submit" class="btn btn-outline-success"><i class="fas fa-save"></i></button>
					<button type="reset" onclick="javascript:toggleEditClassroomTitle();" class="btn btn-outline-danger"><i class="fas fa-times-circle"></i></button>
				</div>
			</div>
		</form>
		<!-- Save button -->
		<button class="btn-sm sideClick general-btn"
		        onclick="window.location.href='{{ url_for('users.classrooms') }}';">
			<i class="fas fa-cloud-upload-alt" aria-hidden="true"></i> Save and Exit
		</button>
	</div>
	<!-- List of added quizzes -->
	<div class="quizlist" id="quizzes-{{classroom.id}}">
		<!-- Heading and add-quiz button -->
		<div id="ActiveRoomsHeader" style="font-size: 2.2vw;">
			<h4 class="Active-Rooms">Added Quizzes</h4>
			<button class="btn-sm sideClick general-btn"
			        onclick="window.location.href='{{ url_for('classrooms.add_quiz', classroom_id=classroom.id) }}';"><i
					class="fas fa-plus" aria-hidden="true" aria-label="add a quiz"></i> Quiz
			</button>
		</div>
		<div style="clear: both;"></div>
		<!-- actual quiz data/options -->
		<table id="added-quizzes-table" class="dt-responsive row-border stripe hover nowrap" style="width: 100%;">
			<thead>
				<tr>
					<td class="text-center">Name</td>
					<td class="text-center">Date Modified</td>
					<td class="text-center">Date Created</td>
					<td class="text-center">Options</td>
				</tr>
			</thead>
			<tbody>
				{% for quiz in classroom.added_quizzes|sort(attribute="name") %}
				<!-- JavaScript option to set the current quiz in the list to active -->
				<tr id="quiz-{{ quiz.id }}" class="table-element">

					<td class="col-4"><a href="{{ url_for('quizzes.quiz', quiz_id=quiz.id) }}">{{ quiz.name }}</a></td>
					<td class="col-4 text-center date-created" style="padding-left: 3%;">{{ quiz.date_modified.strftime("%m/%d/%y") }}</td>
					<td class="col-4 text-center date-created" style="padding-left: 3%;">{{ quiz.date_created.strftime("%m/%d/%y") }}</td>
					<td class="col-4 quiz-icon-col">
						{% if classroom.active_quiz == None %}
						<button id="set-active-btn" data-class="{{classroom.id}}" data-quiz="{{quiz.id}}" class="btn general-btn"
						        data-toggle="modal" data-target="#set_active_modal">
							Set Active
						</button>
						<!-- TODO when un-setting a diff quiz, this one doesn't get activated; also the modal doesn't tell you which quiz you're deactivating -->
						{%include 'editing_quiz_warning_modal.html'%}
						<!-- TODO make this actually remove this quiz from the current classroom, instead of deleting the current classroom -->
						<button data-toggle="tooltip" data-placement="top" title="Unlink this quiz" type="button" class="btn general-btn"
						        aria-label="unlink this quiz">
							<i style="color: darkred;" class="account-page-icons fa fa-lg fa-times" aria-hidden="true"></i><br>
						</button>
						{% elif classroom.active_quiz == quiz.id %}
						{% if classroom.generate_qr %}
						<button class="btn btn-sm btn-outline-info" data-toggle="modal"
						        data-target="#qr_code_modal"> Show QR CODE
						</button>
						{% endif %}
						<button id="remove-active-btn" data-class="{{classroom.id}}" class="btn general-btn">
							Unset Active
						</button>
						{%endif%}
					</td>
				</tr>
				{%endfor%}
			</tbody>
		</table>
	</div>
</div>

{%include 'set_active_modal.html'%}

{% if (current_user.is_authenticated) and (classroom.owner == current_user) %}

{% include 'qr_code_modal.html' %}

<div class="classroom-options">
	{% if classroom.active_quiz %}
	<button id="take-active-quiz" class="btn general-btn"
	        onclick="window.location.href='{{ url_for('classrooms.take_quiz', classroom_id=classroom.id) }}';">Take
		Active Quiz <i class="fas fa-door-open"></i></button>
	{% if has_responses %}
	<button id="view-results" class="btn general-btn"
	        onclick="window.location.href='{{ url_for('classrooms.view_results', classroom_id=classroom.id) }}';"><i
			class="fas fa-chart-bar" aria-hidden="true"></i> View Results
	</button>
	{% endif %}
	<div style="clear: both;"></div>
	{% endif %}
</div>
{% endif %}
<script src="{{url_for('static', filename='js/Classroom.js')}}" type="text/javascript"></script>
{% endblock %}

bettercrative/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
	<meta content="" name="description">
	<meta content="" name="author">

	{% if title %}
	<title>Lightbulb - {{ title }}</title>
	{% else %}
	<title>Lightbulb</title>
	{% endif %}

	<!-- Jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/sunny/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

	<!-- Popper -->
	<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

	<!-- Bootstrap core CSS -->
	<link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
	<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
	        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

	<!-- Mathjax -->
	<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>

	<!-- Custom fonts for this template -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@400&display=swap" rel="stylesheet">

	<!-- CSS -->
	<link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css">

	<!-- CSS for datatables -->
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/dataTables.jqueryui.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.jqueryui.min.css"/>

</head>

<body id="body" class="tex2jax_ignore">
	<main class="page-wrap">
		<!--NavBar-->
		<header>
			<nav class="navbar navbar-expand-lg">
				<a class="navbar-brand" href="{{ url_for('main.home') }}"><h1>Lightbulb</h1></a>
				<button class="navbar-toggler" type="button" data-toggle="collapse"
				        data-target="#navbarSupportedContent"
				        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<div class="navTrigger">
						<span>B</span>
						<span>C</span>
						<span> </span>
					</div>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
						</li>
						{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.classrooms') }}">Classrooms</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.quizzes') }}">Quizzes</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#" data-toggle="modal" data-target="#login-modal">Login</a>
						</li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>
		<!--End Of NavBar-->

		<!-- Home section -->
		<!-- Message flashing -->
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
		{% for category, message in messages %}
		<div class="alert alert-{{ category }}" role="alert">
			{{ message }}
		</div>
		{% endfor %}
		{% endif %}
		{% endwith %}
		<!-- Pop Ups -->
		<div id="modalPopUp" class="modalPopUp" style="display:none;">
			<div class="modalContent">
				<h1 id="modalTitle">
					Please Confirm
				</h1>
				<div id="modalText">
					An unknown error has occurred
				</div>
				<button id="modalButton" type="button" class="btn btn-success">Confirm</button>
				<button id="cancelButton" type="button" class="btn btn-secondary"
				        onclick="document.getElementById('modalPopUp').style.display='none'">Cancel
				</button>
			</div>
		</div>

		<div id="login-modal" class="modal text-center" tabindex="-1" role="dialog">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Log In</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<i class="fa fa-times"></i>
						</button>
					</div>
					<div class="modal-body">
						<a href="{{ url_for('users.login') }}" class="btn btn-lg btn-outline-danger">Teacher</a>
						<a href="{{ url_for('classrooms.enter_classroom') }}" class="btn btn-lg btn-outline-primary">Student</a>
					</div>
				</div>
			</div>
		</div>

		<!-- Page content -->
		{% block content %}
		{% endblock %}
		<!-- End of Home Section -->
	</main>

	<!-- prevent things from floating after this section -->
	<!-- from https://mdbootstrap.com/docs/jquery/navigation/footer/ -->
	<!-- Footer -->
	<footer class="font-small site-footer">

		<!-- Footer Links -->
		<div class="container-fluid text-center text-md-left">

			<!-- Grid row-->
			<div class="row text-center d-flex justify-content-center pt-5 mb-3">

				<!-- Grid column -->
				<div class="col-md-2 mb-3">
					<h6 class="text-uppercase font-weight-bold">
						<a href="#!">About us</a>
					</h6>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-2 mb-3">
					<h6 class="text-uppercase font-weight-bold">
						<a href="#!">Account</a>
					</h6>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-2 mb-3">
					<h6 class="text-uppercase font-weight-bold">
						<a href="#!">Research</a>
					</h6>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-2 mb-3">
					<h6 class="text-uppercase font-weight-bold">
						<a href="#!">Help</a>
					</h6>
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-2 mb-3">
					<h6 class="text-uppercase font-weight-bold">
						<a href="#!">Contact</a>
					</h6>
				</div>
				<!-- Grid column -->

			</div>
			<!-- Grid row-->
			<hr class="rgba-white-light" style="margin: 0 15%;">

			<!-- Grid row-->
			<div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

				<!-- Grid column -->
				<div class=" col-md-8 col-12 mt-3">
					<p> Official Lightbulb </p>
				</div>
				<!-- Grid column -->

			</div>
			<!-- Grid row-->
			<hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

			<!-- Grid row-->
			<div class="row pb-3">

				<!-- Grid column -->
				<div style="margin:auto;">

					<div class="flex-center">

						<!-- Facebook -->
						<a class="fb-ic">
							<i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
						</a>
						<!-- Twitter -->
						<a class="tw-ic">
							<i class="fab fa-twitter fa-lg white-text mr-4"> </i>
						</a>
						<!-- Google +-->
						<a class="gplus-ic">
							<i class="fab fa-google-plus-g fa-lg white-text mr-4"> </i>
						</a>
						<!--Linkedin -->
						<a class="li-ic">
							<i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
						</a>
						<!--Instagram-->
						<a class="ins-ic">
							<i class="fab fa-instagram fa-lg white-text mr-4"> </i>
						</a>
						<!--Pinterest-->
						<a class="pin-ic">
							<i class="fab fa-pinterest fa-lg white-text"> </i>
						</a>

					</div>

				</div>
				<!-- Grid column -->

			</div>
			<!-- Grid row-->

		</div>
		<!-- Footer Links -->

		<!-- Copyright -->
		<div class="footer-copyright text-center py-3">© 2020 Copyright:
			<a href="https://bettercrative.com/"> Lightbulb.com</a>
		</div>
		<!-- Copyright -->

	</footer>
	<!-- Footer -->

	<!-- Global Javascript -->
	<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
	<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.23/js/dataTables.jqueryui.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.jqueryui.min.js"></script>
</body>
</html>